{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "forecast-serving.serviceAccountName" . }}
  labels:
    {{- include "forecast-serving.labels" . | nindent 4 }}
{{- end }}
